---
title: Revisando el paper
author: Fabio
date: '2021-12-18'
slug: revisando-el-paper
categories: ['Research Skills']
tags: [AcWri]
subtitle: 'Modelo mental'
summary: ''
authors: []
lastmod: '2021-12-18T07:00:05+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []

---


Uno de los principles componentes en investigación es poder revisar los escritos que uno hace para un articulo o una conferencia.
Si bien, este proceso de escritura recae en un componente de iteración para poder encontrar los argumentos necesarios, llega el momento de poder corregir aquello que se ha escrito.
Esto no es una tarea fácil.
Revisar el texto que uno genera, necesita claramente una distanciamiento entre uno mismo como un *escritor* y como un *lector*.
Cuando uno escribe es posible que sin darnos cuenta, tengamos ideas o bias que pueden tergiversar nuestras ideas sin más.
Tambien, la congruencia o coherencia de los argumentos, no suelen ser claros en el escrito.
Por ellos Para revisar el texto, Pat Thomson[^1] propose cuatro etapas fundamentales:


1. Leer detalladamente el artículo o el escrito.
1. Diagnosticar los problemas en términos de coherencia y argumentación.
1. Generar soluciones, decidiendo lo que necesita ser resulto en prioridad y en qué orden.
1. Re-escribir el texto.

La tarea de revisar al principio puede ser abrumadora. No saber por donde empezar ni como concluir.
Sin embargo,  estos cuatro procesos pueden facilitar el proceso.
Al hacerlos de manera separada, o inclusive de manera iterativa, pero teniendo en cuenta el objetivo de cada uno, es posible tener un marco mental para emprender la tarea.


Espero sea útil.



[^1]: Revising? try a four step approach. Encontrado en  *https://patthomson.net/2021/11/01/revising-try-a-four-step-approach/*

