- Their potential toxicity is not simply chemically mediated as for most pollutants but driven by very complex, numerous and diverse phenomena (fragmentation, diffusion, interaction and so on) occurring during their extremely long, diverse and obscure lifespans, resulting 

- The success of plastics as a material has been substantial; they have proved versatile for use in a range of types and forms, including natural polymers, modified natural polymers, thermosetting plastics, thermoplastics and, more recently, biodegradable plastics. 

- Plastics have a range of unique properties. 
They can be used at a very wide range of temperatures, are chemical- and light-resistant and they are very strong and tough, but can be easily worked as a hot melt.
They opens up the technical properties in order to sophistication of the product design. 

<!-- Plastics -->
Human society arrived to the plastic age [@Thompson2009a].
Although plastic materials have contributed substantially to societal development, they have increasingly become a paradox for human progress.
Humans have benefited from the use of polymers since approximately 1600 BC, when the ancient Mesoamericans first processed natural rubber into balls, figurines and bands. 
Nevertheless, it was not until the $19^{th}$ that the development of modern synthetic thermoplastics began. 
In 1839, Goodyear developed vulcanized rubber, and Eduard Simon, a German apothecary, discovered polystyrene (PS).
The *Bakelite* was the first truly synthetic polymer developed by Belgian chemist Leo Baekeland in 1907. 
Since then, experimental work have continued on natural/synthetic polymers givin main inventions between the two World Wars: cellophane in 1913, then polyvinyl chloride (PVC) 
in 1927, nylon in 1938, and polyethylene in 1942 [@Andrady2009;@chalmin2019].
The development of synthetic polymers are typically prepared by polymerization of monomers derived from oil or gas. 
These synthetic polymers include several chemical additives to help in the color, processability, thermal/mechanical properties.
It was not until the 1940s and 1950s, that mass production of everyday plastic items really started to take place [@Thompson2009a] and many other plastics were subsequently developed over the next few decades.

However, plastics production and consumption is cause growing — and in some ways existential — risks for people and ecosystems.
Currently, 413 Mt in 2023 is produced worldwide [@plasticseurope2024] and about half of all plastics produced have been made in the last 15 years. 
By 2050, the annual production is projected to increase by 2–3 times arriving to a global plastic production between 902 Mt to 1124 Mt.
It is proved that less than 10% of this production actually have been recycled since 1950 [@Geyer2017].
The compounding effect of plastic waste accumulation in the different ecosystems is an imminent risk for all biotic ecosystems.
Currently, 79% of this widely anthropogenic chemical subtance is accumulated in the environment, having a ubiquitous presence and polluting almost all compartiments of the ecosystem [@bundela2022;@hassan2024].
Indeed, accumulation stock of plastic particles (macro, micro, nano) in the environment is starting to be used as stratigraphic markers in field archaeological practice as indicators of modern or recently disturbed deposits [@zalasiewicz2016]. 
This proves that it is a wicked problem, and one of the main markers of human presence on Earth.


The major contradiction of plastic materials is that, while the first steps related to the production, usage and short-term post-usage (incineration, recycling) are relatively well known, the long-term that occurs after discarding (after reuse and recycling) remain largely unclear in its life cycle. 
After discarding, conventional petrochemical plastics have been discovered behaving differently relative to traditional materials (i.e. metal, wood, glass). 
Plastic wastes do not solubilize slowly like dense materials, such as glass or metals, to reintegrate into silica or iron cycles and mineralize soils and water. 
They are also not digested by the micro-organisms naturally present in soils like natural organic materials, such as paper, cotton and leather, to reintegrate in the natural carbon cycle. 
In other words, *they do not reintegrate into one of the relatively well-known biogeochemical cycles of the elements of our ecosystems* [@gontard2022].
Therefore, this chemical polution is included as one of the planetary boundaries[@oneill2018;@biermann2020], which affects humanity for reminding within the safe operating limits.

In 2022, United Nations Environment Assembly (UNEA) of the United Nations Environment Programme (UNEP) proposed a draft resolution in order to adopt an international legally binding instrument by the year 2024 [@bundela2022]. 
The draft resolution shed ligths on two overarching themes: 
1) responsible consumption and prodution (SDG-12), and 
2) circular economy principles.
UNEA's draft resolution was aimed "*To promote sustainable production and consumption of plastics through, among other things, product design and environmentally sound waste management, including through resource efficiency and circular economy approaches*" [@unep2022].
In principle, 175 member stated on the UN agreed to this proposition [@arora2024].
One of the major advances was to the recognition of the seriousness of micro/nano-plastics (in marine and soil compartiments, and in the human health), which is a transboundary environmental issue [@landrigan2025].
However, after five sessions of the Intergovernmental Negotiation Committee (INC) so far (last at Geneva in August 2025), an agreement that all parties can abide by has remained elusive.
Two main harsh truths were exposed. 
First, even if no state formally objects this agreement, a consensus on the treaty text cannot be reached. 
And second, securing a high-ambition treaty is going to require launching a new process outside the United Nations (UN) framework.


Entering in a more deep analysis of this controverse, it is possible deligthted three main aspect: 
1) defition of the plastic problem, 
2) procedural deadlock and 
3) delays in the ambition of the scope of the treaty [@march2025].

<!-- Definitions -->
Concerning the definition issues, some countries have proposed narrow definition of '*plastic pollution*', limiting the definition to plastic products that have been mismanaged at the of life [@march2025]. 
Indeed, for certain nations, it was about improving waste management, recycling systems and circular economies. 
While for others, it meant curbing the manufacture of primary polymers.
Discrepancies also appeared in importance of the plastic value chain of the nations [@ivanova2025].
Plastics manufacturing implies economic  and political stability for some nations. 
Whereas for small island states and vulnerable coastal areas, plastic pollution threatens human survival. 
The negotiations contrasted the economic realities of some countries with the ecological urgencies tha imply this status-quo in some nations.
This diversity of perspectives in defining the nature of the problem leads to an ambiguity that is part of a geopolitical division.
Another definition issues was the full extent of the 'lifecycle of plastics', where some nations argued a position that lifecyclee begins only after a plastic product has been manufactured.
Fortunalety, a more systemic definition was adopted as: 
*"all the activities and outcomes associated with the production and consumption of plastic materials, products and services — from raw material extraction and processing (refining, cracking, polymerization) to design, manufacturing, packaging, distribution, use (and reuse), maintenance and end-of-life management, including segregation, collection, sorting, recycling and disposal"*.
The implication was that without an appropriated definition of the full lifecycle, the treaty risk to becomeing a *waste-management* agreement rather than a systemic answer tot the plastic pollution [@simon2021]


<!-- 2) procedural deadlock -->
On the other hand, another element to consider relies on the lack of a clear desicion making process
either through voting or consensus.
Consequently, a single dissenting country is at present empowered to veto important decisions.
This allows a small number of countries to block progress, leading, for example, to the blocking of any intersessional work after INC-3 (Nairobi, 2023) and to a substantial reduction in the mandate of the intersessional work agreed at INC-4 (Ottawa, 2024).
When a process works on consensus and you have a few countries refusing to move on certain things, it becomes very difficult to make progress.
Indeed, a number of countries — and UNEP itself — are strongly opposed to the introduction of voting, so that would be challenging to implement.”


Finnaly, the ambition scope remains is major element of controverse. 
A High Ambition Coalition [^1] of countries, more than 100 UN member states, have supported setting global targets for reducing the production of primary plastic polymers to sustainable levels.
In fact, recent research suggests that capping primary plastic production at 2020 levels could significantly curb plastic pollution [@pottinger2024].
Addressing upstream plastic production is essential to ending plastic pollution 
However, the main issue is that a handful of primarily oil-producing countries whose economies are structured around fossil fuels, bolstered by corporations with similar vested interests, opposes production caps and prefers to focus on downstream waste management and recycling instead.

is Scientific studies and material flow modelling clearly demonstrate that 
and protecting health and the environment. 


47 with even more calling for the phasing out of the most harmful plastic products and plastic chemicals

Most stakeholders believe that the role of the High Ambition Coalition (HAC) was often inconsistent in previous rounds of negotiation. 
In the previous INCs, failure to exert unified influence has limited the ability of the HAC to counter low-ambition proposals”

The consensus was not reached on key provisions such as the scope, primary plastic production, problmetaic products and chemicals of concerns. 
It proves this is a wicked problem.




One major evidence is that upstream plastic production is an essential element to end plastic pollutions protecting health and the environment. 
Limiting the plastic production at 2020 levels could significantly curb plastic porduction [@spring2025]







[^1]: [See https://hactoendplasticpollution.org/](https://hactoendplasticpollution.org/)


# References {.unnumbered}