---
title: "Enhancing vibration damping properties of additively manufactured viscoelastic structures through process parameter optimization"
author: 
  - Fangkai Xue
  - Hakim Boudaoud
  - Guillaume Robin  
  - name: Fabio A. Cruz Sanchez
    orcid: 0000-0001-8529-5327
  - El Mostafa Daya 
date: '2023-08-29'
slug: vibration-am-damping-properties
type: article
categories:
  - Research
description: 'Mechanics of Advanced Materials and Structures'
subtitle: 'Present study aims to enhance the damping characteristics of the final part by incorporating viscoelastic materials into the primary structure using multi-material AM.'
abstract: 'With the increasing use of additive manufacturing (AM) in diverse fields, printed structures are inevitably exposed to vibrations, which can result in fracture, fatigue, and noise. Present study aims to enhance the damping characteristics of the final part by incorporating viscoelastic materials into the primary structure using multi-material AM. The effects of process parameters on the vibration damping characteristics of printed viscoelastic structures were investigated through modal analysis and design of experiments. Results show that higher nozzle temperature, smaller layer height, lower deposition speed and smaller raster angle contribute to higher resonant frequencies and loss factors of the final parts.'
links:
- icon: file-richtext-fill
  name: Publication
  url: https://doi.org/10.1080/15376494.2023.2245827
---

## Abstract

With the increasing use of additive manufacturing (AM) in diverse fields, printed structures are inevitably exposed to vibrations, which can result in fracture, fatigue, and noise. Present study aims to enhance the damping characteristics of the final part by incorporating viscoelastic materials into the primary structure using multi-material AM. The effects of process parameters on the vibration damping characteristics of printed viscoelastic structures were investigated through modal analysis and design of experiments. Results show that higher nozzle temperature, smaller layer height, lower deposition speed and smaller raster angle contribute to higher resonant frequencies and loss factors of the final parts.